"""Report to Markdown. The second backend, and the reason `views.py` produces no markup.

ADR-028 claims that the specs-and-views split lets a different frontend reuse every view
untouched. This file is that claim being cashed: the same `Report` objects that become a
self-contained HTML page become a Markdown document here, and no view knows the
difference. Nothing in `views.py` or `forward_views.py` changed to make it work.

What it is for
--------------
The HTML set is the deliverable. Markdown is the version that pastes into an email, an
issue, a commit message or a terminal - and the version that still reads correctly in
ten years when nothing renders SVG the way it does today. Both are generated from one
source, so a summary can never drift from the report it summarises, which is exactly
what happens when someone hand-writes the executive version.

Charts
------
A line chart has no honest Markdown form, so it is described rather than faked: title,
subtitle, series names, the span they cover and the caption. Bar charts and heatmaps DO
have one - they are small grids of numbers - so those are rendered as tables and lose
nothing. A scatter becomes a table of its points.

The rule throughout: never emit a shape that implies precision the format cannot carry.
An ASCII sparkline would look like data and be an artefact of column width.
"""

from __future__ import annotations

import math

from ..specs import (AreaChart, BarChart, Download, Heatmap, LineChart, LinkGrid,
                     Note, Report, ScatterChart, Section, StatRow, TableBlock)
from ..tables import Table

#: Beyond this many rows a table is truncated with a note. Markdown tables stop being
#: readable long before they stop being valid, and the HTML report has the full one.
MAX_TABLE_ROWS = 60

_NOTE_PREFIX = {"info": "**Note.**", "warn": "**⚠ Warning.**",
                "danger": "**⛔ Important.**"}


def render(report: Report) -> str:
    """The whole document as one Markdown string."""
    out = [f"# {report.title}"]
    if report.subtitle:
        out.append(f"*{report.subtitle}*")
    if report.meta:
        out.append(" · ".join(f"**{k}:** {v}" for k, v in report.meta.items()))
    if report.generated_at:
        out.append(f"<sub>generated {report.generated_at}</sub>")
    out.append("")
    out.append(_contents(report))
    for section in report.sections:
        out.append(_section(section))
    out.append("---")
    out.append("<sub>Generated by `sp500lab report forward`. Every number comes from "
               "`data/experiments/forward/`; nothing here was transcribed by hand.</sub>")
    return "\n\n".join(part for part in out if part) + "\n"


def write(report: Report, path) -> "object":
    from pathlib import Path
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(render(report), encoding="utf-8")
    return p


# --------------------------------------------------------------------------
# Structure
# --------------------------------------------------------------------------

def _contents(report: Report) -> str:
    if len(report.sections) < 3:
        return ""
    items = "\n".join(f"{i}. [{s.title}](#{s.anchor})"
                      for i, s in enumerate(report.sections, 1))
    return "**Contents**\n\n" + items


def _section(section: Section) -> str:
    parts = [f'<a id="{section.anchor}"></a>', f"## {section.title}"]
    if section.blurb:
        parts.append(section.blurb)
    for block in section.blocks:
        rendered = _block(block)
        if rendered:
            parts.append(rendered)
    return "\n\n".join(parts)


def _block(block) -> str:
    if isinstance(block, Note):
        return _note(block)
    if isinstance(block, StatRow):
        return _stat_row(block)
    if isinstance(block, TableBlock):
        return _table_block(block)
    if isinstance(block, Download):
        return _download(block)
    if isinstance(block, LinkGrid):
        return _link_grid(block)
    if isinstance(block, BarChart):
        return _bar_chart(block)
    if isinstance(block, Heatmap):
        return _heatmap(block)
    if isinstance(block, ScatterChart):
        return _scatter(block)
    if isinstance(block, (LineChart, AreaChart)):
        return _described_chart(block)
    raise TypeError(f"no Markdown for block {type(block).__name__}")


# --------------------------------------------------------------------------
# Blocks
# --------------------------------------------------------------------------

def _note(note: Note) -> str:
    head = _NOTE_PREFIX.get(note.level, "**Note.**")
    title = f" {note.title}" if note.title else ""
    body = note.text.replace("\n", " ")
    return f"> {head}{title} {body}"


def _stat_row(block: StatRow) -> str:
    head = f"**{block.title}**\n\n" if block.title else ""
    cells = [f"| {s.label} | **{s.value}**"
             + (f" <br><sub>{s.note}</sub>" if s.note else "") + " |"
             for s in block.stats]
    return head + "| | |\n|---|---|\n" + "\n".join(cells)


def _table_block(block: TableBlock) -> str:
    head = f"**{block.title}**\n\n" if block.title else ""
    return head + _table(block.table)


def _table(table: Table) -> str:
    if table.empty:
        return "*(no rows)*"
    header = "| " + " | ".join(_escape(c) for c in table.columns) + " |"
    align = "|" + "|".join(_align(a) for a in table.aligns) + "|"
    rows = table.rows[:MAX_TABLE_ROWS]
    body = "\n".join(
        "| " + " | ".join(_cell(c) for c in row) + " |" for row in rows)
    out = "\n".join([header, align, body])
    if len(table.rows) > MAX_TABLE_ROWS:
        out += (f"\n\n*{len(table.rows) - MAX_TABLE_ROWS} further row(s) omitted; the "
                "HTML report has all of them.*")
    if table.caption:
        out += f"\n\n<sub>{table.caption}</sub>"
    return out


def _cell(cell) -> str:
    text = _escape(cell.text)
    if cell.href:
        text = f"[{text}]({cell.href})"
    if cell.emphasis in ("good", "bad"):
        text = f"**{text}**"
    return text or "—"


def _align(a: str) -> str:
    return {"left": ":---", "right": "---:", "center": ":---:"}.get(a, "---")


def _download(block: Download) -> str:
    """A pointer, not a payload. A data URI in Markdown helps nobody."""
    return (f"**{block.label}:** `{block.filename}`"
            + (f" — {block.note}" if block.note else "")
            + "\n\n<sub>Embedded in the HTML version of this report; on disk under "
              "`results/forward/`.</sub>")


def _link_grid(block: LinkGrid) -> str:
    head = f"**{block.title}**\n\n" if block.title else ""
    items = []
    for card in block.cards:
        stats = " · ".join(f"{k} {v}" for k, v in card.stats)
        line = f"- [{card.title}]({card.href})"
        if card.blurb:
            line += f" — {card.blurb}"
        if stats:
            line += f"  \n  <sub>{stats}</sub>"
        items.append(line)
    return head + "\n".join(items)


def _bar_chart(block: BarChart) -> str:
    head = f"**{block.title}**\n\n" if block.title else ""
    rows = "\n".join(f"| {_escape(label)} | {_fmt(value, block.y_format)} |"
                     for label, value in zip(block.labels, block.values))
    out = head + "| | |\n|:---|---:|\n" + rows
    if block.caption:
        out += f"\n\n<sub>{block.caption}</sub>"
    return out


def _heatmap(block: Heatmap) -> str:
    head = f"**{block.title}**\n\n" if block.title else ""
    header = "| | " + " | ".join(_escape(c) for c in block.cols) + " |"
    align = "|:---|" + "|".join("---:" for _ in block.cols) + "|"
    body = "\n".join(
        f"| **{_escape(label)}** | "
        + " | ".join(_fmt(v, block.value_format) for v in row) + " |"
        for label, row in zip(block.rows, block.values))
    out = head + "\n".join([header, align, body])
    if block.caption:
        out += f"\n\n<sub>{block.caption}</sub>"
    return out


def _scatter(block: ScatterChart) -> str:
    head = f"**{block.title}**\n\n" if block.title else ""
    header = (f"| point | {_escape(block.x_label or 'x')} | "
              f"{_escape(block.y_label or 'y')} |")
    rows = "\n".join(
        f"| {_escape(p.label)} | {_fmt(p.x, block.x_format)} | "
        f"{_fmt(p.y, block.y_format)} |" for p in block.points)
    out = head + "\n".join([header, "|:---|---:|---:|", rows])
    if block.caption:
        out += f"\n\n<sub>{block.caption}</sub>"
    return out


def _described_chart(block) -> str:
    """A line or area chart, described rather than faked.

    There is no honest Markdown rendering of a time series, and an ASCII sparkline would
    look like data while being an artefact of the column width. So this says what the
    chart shows, over what span, and repeats the caption - which is the part a reader
    would have taken away anyway.
    """
    series = block.series if isinstance(block.series, list) else [block.series]
    series = [s for s in series if s is not None and len(s)]
    title = block.title or "Chart"
    lines = [f"**{title}** *(chart — see the HTML report)*"]
    if getattr(block, "subtitle", ""):
        lines.append(block.subtitle)
    for s in series:
        last = s.last()
        span = f"{s.x[0]} → {s.x[-1]}" if s.x else "—"
        tail = f", ending at {last:,.3f}" if last is not None else ""
        lines.append(f"- **{s.name}** ({s.kind}): {len(s)} points, {span}{tail}")
    if getattr(block, "caption", ""):
        lines.append(f"<sub>{block.caption}</sub>")
    return "\n\n".join(lines[:2]) + "\n" + "\n".join(lines[2:])


# --------------------------------------------------------------------------
# Formatting
# --------------------------------------------------------------------------

def _fmt(value, kind: str) -> str:
    if value is None or (isinstance(value, float) and not math.isfinite(value)):
        return "—"
    try:
        v = float(value)
    except (TypeError, ValueError):
        return _escape(str(value))
    if kind == "pct":
        return f"{v * 100:.2f}%"
    if kind == "bp":
        return f"{v * 1e4:.1f}bp"
    if kind == "money":
        return f"${v:,.0f}"
    if kind == "multiple":
        return f"{v:.2f}x"
    if kind == "count":
        return f"{v:,.0f}"
    return f"{v:.2f}"


def _escape(text) -> str:
    """Pipes break a Markdown table row; nothing else in this data needs escaping."""
    return str(text).replace("|", "\\|").replace("\n", " ")
